In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import misc
from PIL import Image

C:\Users\kasum\AppData\Local\Temp\ipykernel_12324\3926729499.py:4: DeprecationWarning: scipy.misc is deprecated and will be removed in 2.0.0
  from scipy import misc


In [7]:
# 1 dimensional array
my_array = np.array([1.1, 9.2, 8.1, 4.7])
my_array.shape

(4,)

In [8]:
my_array[2]

np.float64(8.1)

In [9]:
my_array.ndim

1

In [11]:
array_2d = np.array([[1,2,4,5,6],[8,5,9,10,30]])
array_2d.ndim

2

In [12]:
array_2d[1,2]

np.int64(9)

In [13]:
array_2d.shape

(2, 5)

In [14]:
array_2d[0, :]

array([1, 2, 4, 5, 6])

In [15]:
# tensor
mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],

                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

In [17]:
mystery_array.ndim

3

In [19]:
mystery_array[:, :, 0]

array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])

In [30]:
a = np.arange(10,30)
a[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [31]:
np.flip(a)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [33]:
image = misc.face()
plt.imshow(image)

AttributeError: module 'scipy.misc' has no attribute 'face'